// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using YoutubeK;

namespace YoutubeK.Migrations
{
    [DbContext(typeof(YoutubekDbContext))]
    [Migration("20180311070819_addMasterkey")]
    partial class addMasterkey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("YoutubeK.Models.Channel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsActive");

                    b.Property<string>("MetaData");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("YoutubeK.Models.Karaoke", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Channel");

                    b.Property<string>("ChannelId");

                    b.Property<string>("FixBy");

                    b.Property<string>("Flag");

                    b.Property<string>("FlagBy");

                    b.Property<int>("IsHQ");

                    b.Property<string>("MetaData");

                    b.Property<string>("ReplaceId");

                    b.Property<string>("Status");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Karaokes");
                });

            modelBuilder.Entity("YoutubeK.Models.Room", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateLastActive");

                    b.Property<int>("GuestCount");

                    b.Property<string>("MasterIp");

                    b.Property<string>("MasterKey");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
